name: Run Ptester with Timeout

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-ptester:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # whole job limit safeguard (6h)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install requests aiohttp urllib3

      - name: Run Ptester.py (with 5h40m limit)
        run: |
          timeout 20400s python Ptester.py || echo "Ptester stopped due to timeout"
        # 20400s = 5 hours 40 minutes

      - name: Upload generated files as artifact
        if: always()   # runs even if timeout happens
        uses: actions/upload-artifact@v4
        with:
          name: ptester-results
          path: |
            **/*.txt
            **/*.log
            output/**

      - name: Commit and push generated files
        if: always()   # ensure push even on timeout
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Partial results from Ptester.py (timeout-safe) [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
