# .github/workflows/ptester.yml
name: Run Ptester (Ubuntu)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-ptester:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Install curl (ensures curl exists)
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (if any)
        run: python -m pip install --upgrade pip

      - name: Run proxy tester (timeout 5h40m)
        id: run_ptester
        continue-on-error: true
        run: |
          timeout 20400s python proxy_tester_curl_multiport.py --count 200 --max-workers 50 --timeout 3
          rc=$?; echo "rc=$rc"; if [ $rc -eq 124 ]; then echo "timed_out=true" >> $GITHUB_OUTPUT; fi

      - name: Ensure results summary exists
        run: |
          mkdir -p results
          echo "Run completed at $(date -u)" > results/summary.txt
          echo "Script rc: ${{ steps.run_ptester.outputs.rc }}" >> results/summary.txt || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ptester-results
          path: results/**

      - name: Commit & push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add results || true
          git commit -m "Add Ptester results [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }} || echo "Push failed"
